### PR TITLE
Added models for SQS events

### PR DESCRIPTION
**Pull request by meyer1994**
Created the events in this PR based on the example from this [link](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html). There may be something missing, I did not tested it by deploying

### CODE REVIEW

**Comment by koxudaxi** [comment]
@meyer1994 
Thank you for creating this PR.

I created a new repository to pool pedantic models. 
https://github.com/koxudaxi/pydantic-collection

I have a plan This repository can have any `pydantic` model.

How do you think about this idea?

**Comment by meyer1994** [comment]
It is not a bad idea. But it is ambitious :)

My vision, when I went searching for the `lambdantic` name, was to create a very simple event model collection to be used in lambdas. Even as a reference, because AWS documentation lacks some things and I am always rewriting these classes in projects.

I wanted a library that could be used like this:

```python
from pydantic import BaseModel, Json

from lambdantic.sns import Event

class MyMessage(BaseModel):
    attr1: str
    attr2: int

class MyEvent(Event):
    Message: Json[MyMessage]

def handler(event, context):
    event = MyEvent(**event)
```

Looking back now, many of the models I've created for SNS probably won't be used in lambdas :P

Your vision for lambdantic is a bit more complex than mine. You've created a API gateway router with pydantic support builtin. Which is awesome! Very similar to [FastAPI](https://github.com/tiangolo/fastapi).

Briefly, my vision was to create an event model collection to be used in lambdas, as described in the above example. The other (big) collection seems cool though. You could implement it like a package aggregator:

```bash
$ pip install pydantic-collection[aws]
$ pip install pydantic-collection[azure]
# etc...
```

Either way. You decide. They are your packages :)

I am willing to help either way!

**Comment by koxudaxi** [comment]
@meyer1994 
I agree. 

I use this code for mapping an event of SQS.
I will publish this decorator on a repository.
```python
EventType = TypeVar('EventType', bound=Event)

if TYPE_CHECKING:
    Handler = Callable[[Dict[str, Any], Context], Any]
    EventTypedHandler = Callable[[EventType, Context], Any]


def event_mapper(event_model: Type[EventType]) -> Callable[[Handler], Any]:
    def receive_func(
        handler: EventTypedHandler,
    ) -> Callable[[Handler], EventTypedHandler]:
        @wraps(handler)
        def inner(event: Dict[str, Any], context: Context) -> Any:
            parsed_event: EventType = event_model.parse_obj(event)
            return handler(parsed_event, context)

        return inner

@event_mapper(Event)
def handle(event: Event, _: Context) -> None:
   pass
```
> Your vision for lambdantic is a bit more complex than mine. You've created a API gateway router with pydantic support builtin. Which is awesome! Very similar to FastAPI.

Yes, My first challenge was to create a similar library to FastAPI.
But, I considered and I am using FastAPI + Magnum(https://github.com/erm/mangum).
Also, I contributed to each library :)

I had dropped this plan which to create FastAPI style event dispatcher.
However, recently a few people give starts to this repository.
I want to know what do they need? models? dispatcher? :thinking: 

> Either way. You decide. They are your packages :)

Thank you. Let me sleep on it :sleeping_bed:

**Comment by meyer1994** [comment]
> However, recently a few people give starts to this repository.
> I want to know what do they need? models? dispatcher? thinking

I understand. Maybe they want a dispatcher, but is it necessairy? FastAPI, in my opinion, is very good already.

I, a random dude on the internet, want a collection of events. Hehehe.

**Comment by koxudaxi** [comment]
@meyer1994 
I have released a new version(0.0.4) which includes your PRs.
I will move models to the [pydantic-collection](https://github.com/koxudaxi/pydantic-collection) repository this week.

I don't decide about this repository:thinking: 

Thank you for creating these PRs. I'm looking forward to PRs next time :wink:

**Pull request merged**
